import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedStateRequirements() {
  console.log('  🗺️  Seeding state requirements...');

  const existingCount = await prisma.stateRequirements.count();
  if (existingCount > 0) {
    console.log('  ⏭️  State requirements already seeded, skipping...');
    return;
  }

  // Helper to create standard state requirement (with sensible defaults)
  const createStateReq = (overrides: any) => ({
    notarizationRequired: true,
    notarizationStronglyRec: false,
    witnessesRequired: false,
    numberOfWitnesses: null,
    minimumWitnessAge: 18,
    witnessesOrNotary: false,
    agentCannotBeWitness: false,
    notaryCannotBeWitness: false,
    spouseCannotBeWitness: false,
    relativesCannotBeWitness: false,
    witnessRestrictions: null,
    hasStatutoryForm: false,
    statutoryFormRequired: false,
    statutoryFormCitation: null,
    statutoryFormNotes: null,
    durabilityRequired: true,
    durabilityWording: 'This power of attorney shall not be affected by subsequent disability or incapacity of the principal.',
    defaultDurability: 'durable',
    allowsSpringing: true,
    springingBannedReason: null,
    numberOfPhysiciansRequired: 1,
    courtDeterminationAllowed: false,
    requiresAgentSignature: false,
    requiresAgentNotarization: false,
    agentAcceptanceWording: null,
    requiredPrincipalNotice: null,
    requiredAgentNotice: null,
    recordingMandatoryFor: null,
    recordingInstructions: null,
    estimatedRecordingFee: null,
    hotPowersRequireSeparateConsent: false,
    hotPowersList: null,
    giftingAnnualLimit: null,
    specialNotes: null,
    strictnessLevel: 'standard',
    allowsRemoteNotarization: true,
    ...overrides
  });

  const states = [
    // ============================================
    // PRIORITY STATES - VERY DETAILED (From your file)
    // ============================================
    
    createStateReq({
      state: 'FL',
      stateName: 'Florida',
      witnessesRequired: true,
      numberOfWitnesses: 2,
      agentCannotBeWitness: true,
      spouseCannotBeWitness: true,
      relativesCannotBeWitness: true,
      witnessRestrictions: 'Witnesses cannot be: attorney-in-fact (agent), spouse, children, or blood relatives of the principal.',
      hasStatutoryForm: true,
      statutoryFormRequired: true,
      statutoryFormCitation: 'Fla. Stat. §709.2102',
      statutoryFormNotes: 'Florida requires use of the exact statutory form. Custom POA forms will likely be rejected by banks and title companies.',
      durabilityWording: 'This durable power of attorney is not affected by subsequent incapacity of the principal.',
      allowsSpringing: false,
      springingBannedReason: 'Florida banned springing POAs after 2011 (Fla. Stat. §709.08)',
      numberOfPhysiciansRequired: null,
      requiredPrincipalNotice: 'NOTICE: THE POWERS GRANTED BY THIS DOCUMENT ARE BROAD AND SWEEPING...',
      requiredAgentNotice: 'AGENT\'S DUTIES: When you accept the authority granted under this power of attorney...',
      recordingMandatoryFor: ['real_estate'],
      recordingInstructions: 'Must be recorded with county clerk in county where property is located before use for real estate transactions',
      estimatedRecordingFee: 30.00,
      hotPowersRequireSeparateConsent: true,
      hotPowersList: ['gifts', 'trust_modification', 'beneficiary_changes', 'homestead_transactions'],
      giftingAnnualLimit: 18000.00,
      specialNotes: 'Florida is VERY STRICT. Must use statutory form §709.2102. Agent duties clause recommended. Recording mandatory for real estate.',
      strictnessLevel: 'very_strict'
    }),

    createStateReq({
      state: 'TX',
      stateName: 'Texas',
      agentCannotBeWitness: true,
      witnessRestrictions: 'Witnesses not required, but if used, agent cannot be witness.',
      hasStatutoryForm: true,
      statutoryFormRequired: true,
      statutoryFormCitation: 'Tex. Estates Code §752.051',
      statutoryFormNotes: 'Texas statutory durable POA form strongly recommended for acceptance by institutions.',
      durabilityWording: 'This power of attorney is not affected by subsequent disability or incapacity of the principal.',
      requiredPrincipalNotice: 'NOTICE: THE POWERS GRANTED BY THIS DOCUMENT ARE BROAD AND SWEEPING...',
      requiredAgentNotice: 'IMPORTANT INFORMATION FOR AGENT: Agent\'s Duties...',
      recordingMandatoryFor: ['real_estate'],
      recordingInstructions: 'Record with county clerk where property located',
      estimatedRecordingFee: 35.00,
      hotPowersRequireSeparateConsent: true,
      hotPowersList: ['gifts', 'trust_modification', 'beneficiary_changes'],
      giftingAnnualLimit: 18000.00,
      specialNotes: 'Texas has detailed statutory form. Digital assets explicitly included. Springing requires physician certification.',
      strictnessLevel: 'strict'
    }),

    createStateReq({
      state: 'CA',
      stateName: 'California',
      witnessesOrNotary: true,
      agentCannotBeWitness: true,
      witnessRestrictions: 'Notary OR 2 witnesses. If witnesses used, one witness cannot be agent or related to principal.',
      hasStatutoryForm: true,
      statutoryFormCitation: 'Cal. Probate Code §4401',
      statutoryFormNotes: 'California statutory short form strongly recommended but not mandatory.',
      durabilityWording: 'This power of attorney shall not be affected by subsequent incapacity of the principal.',
      defaultDurability: 'non-durable', // CA defaults to non-durable!
      numberOfPhysiciansRequired: 2,
      requiresAgentSignature: true,
      agentAcceptanceWording: 'BY ACCEPTING OR ACTING UNDER THE APPOINTMENT, THE AGENT ASSUMES THE FIDUCIARY AND OTHER LEGAL RESPONSIBILITIES OF AN AGENT.',
      requiredPrincipalNotice: 'NOTICE: THE POWERS GRANTED BY THIS DOCUMENT ARE BROAD AND SWEEPING...',
      recordingInstructions: 'Recording optional but recommended for real estate transactions',
      estimatedRecordingFee: 30.00,
      giftingAnnualLimit: 18000.00,
      specialNotes: 'California defaults to NON-DURABLE unless durability clause included. Penalty of perjury notary form unique to CA. Agent signature required when using POA.',
      strictnessLevel: 'strict'
    }),

    createStateReq({
      state: 'NY',
      stateName: 'New York',
      witnessesRequired: true,
      numberOfWitnesses: 2,
      agentCannotBeWitness: true,
      notaryCannotBeWitness: true,
      witnessRestrictions: '2 witnesses required. Agent and notary cannot be witnesses.',
      hasStatutoryForm: true,
      statutoryFormRequired: true,
      statutoryFormCitation: 'N.Y. Gen. Oblig. Law §5-1501',
      statutoryFormNotes: 'Must use 2021 statutory short form. Banks in NY are extremely strict about form compliance.',
      durabilityWording: 'This power of attorney shall not be affected by my subsequent incapacity.',
      requiresAgentSignature: true,
      requiresAgentNotarization: true,
      agentAcceptanceWording: 'I have read the foregoing Power of Attorney. I am the person identified therein as agent for the principal named therein.',
      requiredPrincipalNotice: 'CAUTION TO THE PRINCIPAL: Your Power of Attorney is an important document...',
      requiredAgentNotice: 'IMPORTANT INFORMATION FOR THE AGENT...',
      recordingMandatoryFor: ['real_estate'],
      recordingInstructions: 'Must record with county clerk. Revocation must also be recorded if original was recorded.',
      estimatedRecordingFee: 50.00,
      hotPowersRequireSeparateConsent: true,
      hotPowersList: ['gifts_over_annual_exclusion'],
      giftingAnnualLimit: 18000.00,
      specialNotes: 'NEW YORK IS EXTREMELY STRICT. Must use 2021 statutory form. Agent must sign/notarize separately. Gifts over $18K require separate notarized Gifts Rider. Monitor designation option available.',
      strictnessLevel: 'very_strict'
    }),

    createStateReq({
      state: 'NC',
      stateName: 'North Carolina',
      witnessesRequired: true,
      numberOfWitnesses: 2,
      agentCannotBeWitness: true,
      witnessRestrictions: 'Agent cannot be witness.',
      hasStatutoryForm: true,
      statutoryFormCitation: 'N.C. Gen. Stat. §32C-1-105',
      statutoryFormNotes: 'Statutory form recommended and widely used.',
      recordingMandatoryFor: ['real_estate'],
      recordingInstructions: 'Must record with register of deeds in county where property located',
      estimatedRecordingFee: 26.00,
      specialNotes: 'Must record POA if used for real estate. Health care POA separate document.',
      strictnessLevel: 'strict'
    }),

    createStateReq({
      state: 'GA',
      stateName: 'Georgia',
      witnessesRequired: true,
      numberOfWitnesses: 2,
      recordingMandatoryFor: ['real_estate'],
      recordingInstructions: 'Record with clerk of superior court in county where property located',
      estimatedRecordingFee: 30.00,
      giftingAnnualLimit: 18000.00,
      specialNotes: 'Georgia allows custom forms but strict recording requirements for real estate.'
    }),

    createStateReq({
      state: 'IL',
      stateName: 'Illinois',
      witnessesRequired: true,
      numberOfWitnesses: 1,
      agentCannotBeWitness: true,
      relativesCannotBeWitness: true,
      witnessRestrictions: 'Witness cannot be: agent, attending physician, mental health provider, relative of physician, owner/operator of healthcare facility, parent/sibling/descendant of principal or agent.',
      hasStatutoryForm: true,
      statutoryFormRequired: true,
      statutoryFormCitation: '755 ILCS 45/3-3',
      statutoryFormNotes: 'Must use Illinois Statutory Short Form Property POA. Exact statutory short form with initials for each power.',
      durabilityWording: 'This power of attorney shall not be affected by disability of the principal.',
      requiredPrincipalNotice: 'NOTICE TO THE INDIVIDUAL SIGNING THE ILLINOIS STATUTORY SHORT FORM...',
      requiredAgentNotice: 'NOTICE TO AGENT: POWER OF ATTORNEY FOR PROPERTY...',
      recordingMandatoryFor: ['real_estate'],
      recordingInstructions: 'Record with county recorder in county where property located',
      estimatedRecordingFee: 35.00,
      hotPowersRequireSeparateConsent: true,
      hotPowersList: ['gifts', 'trust_modification', 'beneficiary_changes'],
      giftingAnnualLimit: 18000.00,
      specialNotes: 'Illinois has detailed witness restrictions. Agent certification form required for third parties to accept POA.',
      strictnessLevel: 'strict'
    }),

    createStateReq({
      state: 'PA',
      stateName: 'Pennsylvania',
      witnessesRequired: true,
      numberOfWitnesses: 2,
      agentCannotBeWitness: true,
      witnessRestrictions: 'Agent cannot be witness.',
      hasStatutoryForm: true,
      statutoryFormRequired: true,
      statutoryFormCitation: '20 Pa.C.S. §5601',
      statutoryFormNotes: 'Must include mandatory notice to principal on front page and agent acknowledgment.',
      requiresAgentSignature: true,
      agentAcceptanceWording: 'I accept this appointment and agree to act in the principal\'s best interest as authorized in this power of attorney.',
      requiredPrincipalNotice: 'When you accept the authority granted under this power of attorney, a special legal relationship is created between you and the principal...',
      requiredAgentNotice: 'IMPORTANT INFORMATION FOR THE AGENT: Agent\'s duties...',
      recordingMandatoryFor: ['real_estate'],
      recordingInstructions: 'Record with office of recorder of deeds in county where property located',
      estimatedRecordingFee: 40.00,
      hotPowersRequireSeparateConsent: true,
      hotPowersList: ['gifts', 'trust_modification', 'beneficiary_changes'],
      giftingAnnualLimit: 18000.00,
      specialNotes: 'Pennsylvania requires verbatim front-page notice. Agent must sign acknowledgment. Interstate: Recognizes other states\' POAs but requires PA-compliant notice for use in PA.',
      strictnessLevel: 'strict'
    }),

    createStateReq({
      state: 'OH',
      stateName: 'Ohio',
      agentCannotBeWitness: true,
      witnessRestrictions: 'Witnesses not required.',
      durabilityWording: 'This power of attorney shall not be affected by disability of the principal.',
      recordingInstructions: 'Recording optional but recommended for real estate',
      estimatedRecordingFee: 28.00,
      giftingAnnualLimit: 18000.00,
      specialNotes: 'Ohio allows custom forms. No witnesses required.'
    }),

    createStateReq({
      state: 'AZ',
      stateName: 'Arizona',
      witnessesRequired: true,
      numberOfWitnesses: 1,
      witnessesOrNotary: true,
      agentCannotBeWitness: true,
      witnessRestrictions: '1 witness OR none if notarized. Agent cannot be witness.',
      durabilityWording: 'This power of attorney shall not be affected by disability of the principal.',
      numberOfPhysiciansRequired: 2,
      courtDeterminationAllowed: true,
      recordingInstructions: 'Recording optional but recommended for real estate',
      estimatedRecordingFee: 25.00,
      giftingAnnualLimit: 18000.00,
      specialNotes: 'Arizona has flexible witness requirements. Springing POA can use 1-2 physicians OR court determination.'
    }),

    createStateReq({
      state: 'AK',
      stateName: 'Alaska',
      witnessesRequired: true,
      numberOfWitnesses: 1,
      agentCannotBeWitness: true,
      witnessRestrictions: 'One witness required (cannot be agent). If for real estate, must use 2 witnesses or notarization.',
      hasStatutoryForm: false,
      statutoryFormRequired: false,
      durabilityWording: 'This power of attorney shall not be affected by subsequent disability or incapacity of the principal.',
      numberOfPhysiciansRequired: 1,
      courtDeterminationAllowed: true,
      recordingMandatoryFor: ['real_estate'],
      recordingInstructions: 'Must record with district recorder in judicial district where property located. Real estate POAs require either 2 witnesses OR notarization.',
      estimatedRecordingFee: 40.00,
      hotPowersRequireSeparateConsent: false,
      giftingAnnualLimit: 18000.00,
      specialNotes: 'Alaska allows custom forms. Real estate transactions require stricter execution: 2 witnesses OR notary. General POAs only need 1 witness. Remote notarization permitted.',
      strictnessLevel: 'standard'
    }),

    createStateReq({
      state: 'TN',
      stateName: 'Tennessee',
      witnessesRequired: true,
      numberOfWitnesses: 2,
      agentCannotBeWitness: true,
      notaryCannotBeWitness: false,
      spouseCannotBeWitness: false,
      relativesCannotBeWitness: false,
      witnessRestrictions: 'Two witnesses required. Agent cannot be witness. At least one witness should not be related to principal by blood or marriage (recommended).',
      hasStatutoryForm: true,
      statutoryFormRequired: false,
      statutoryFormCitation: 'Tenn. Code Ann. §34-6-101 et seq.',
      statutoryFormNotes: 'Tennessee statutory form available but not required. Statutory form provides safe harbor and is widely accepted.',
      durabilityWording: 'This power of attorney shall not be affected by my subsequent disability or incapacity.',
      numberOfPhysiciansRequired: 1,
      courtDeterminationAllowed: true,
      requiresAgentSignature: false,
      requiresAgentNotarization: false,
      requiredPrincipalNotice: 'NOTICE TO PRINCIPAL: This is an important legal document...',
      requiredAgentNotice: 'IMPORTANT INFORMATION FOR AGENT: When you accept the authority granted under this power of attorney...',
      recordingMandatoryFor: ['real_estate'],
      recordingInstructions: 'Must record with Register of Deeds in county where property located. Recording fees vary by county.',
      estimatedRecordingFee: 32.00,
      hotPowersRequireSeparateConsent: true,
      hotPowersList: ['gifts', 'trust_modification', 'beneficiary_changes', 'delegation'],
      giftingAnnualLimit: 18000.00,
      specialNotes: 'Tennessee follows UPOAA (Uniform Power of Attorney Act). Statutory form recommended for institutional acceptance. Banks typically require statutory form. Health care POA is separate document.',
      strictnessLevel: 'strict'
    }),

    // ============================================
    // REMAINING 39 STATES - STANDARD DATA
    // ============================================

    createStateReq({ state: 'AL', stateName: 'Alabama', witnessesRequired: true, numberOfWitnesses: 2, agentCannotBeWitness: true, witnessRestrictions: 'Agent cannot serve as witness' }),
    createStateReq({ state: 'AR', stateName: 'Arkansas', witnessesRequired: true, numberOfWitnesses: 2, agentCannotBeWitness: true, witnessRestrictions: 'Agent cannot serve as witness', hasStatutoryForm: true, statutoryFormCitation: '§28-68-104' }),
    createStateReq({ state: 'CO', stateName: 'Colorado', hasStatutoryForm: true, statutoryFormCitation: '§15-14-705' }),
    createStateReq({ state: 'CT', stateName: 'Connecticut', witnessesRequired: true, numberOfWitnesses: 2, agentCannotBeWitness: true, witnessRestrictions: 'Agent cannot serve as witness', hasStatutoryForm: true, statutoryFormCitation: '§1-350b', strictnessLevel: 'strict' }),
    createStateReq({ state: 'DE', stateName: 'Delaware', witnessesRequired: true, numberOfWitnesses: 2, agentCannotBeWitness: true, witnessRestrictions: 'Agent cannot serve as witness' }),
    createStateReq({ state: 'DC', stateName: 'District of Columbia', hasStatutoryForm: true, statutoryFormCitation: '§21-2081' }),
    createStateReq({ state: 'HI', stateName: 'Hawaii', hasStatutoryForm: true, statutoryFormCitation: '§551D-2.5' }),
    createStateReq({ state: 'ID', stateName: 'Idaho', strictnessLevel: 'lenient' }),
    createStateReq({ state: 'IN', stateName: 'Indiana', hasStatutoryForm: true, statutoryFormCitation: 'IC 30-5-5-2' }),
    createStateReq({ state: 'IA', stateName: 'Iowa', hasStatutoryForm: true, statutoryFormCitation: '§633B.201' }),
    createStateReq({ state: 'KS', stateName: 'Kansas', hasStatutoryForm: true, statutoryFormCitation: '§58-652' }),
    createStateReq({ state: 'KY', stateName: 'Kentucky', strictnessLevel: 'lenient' }),
    createStateReq({ state: 'LA', stateName: 'Louisiana', witnessesRequired: true, numberOfWitnesses: 2, agentCannotBeWitness: true, witnessRestrictions: 'Agent cannot serve as witness' }),
    createStateReq({ state: 'ME', stateName: 'Maine', hasStatutoryForm: true, statutoryFormCitation: '18-C §5-501' }),
    createStateReq({ state: 'MD', stateName: 'Maryland', witnessesRequired: true, numberOfWitnesses: 2, agentCannotBeWitness: true, witnessRestrictions: 'Agent cannot serve as witness' }),
    createStateReq({ state: 'MA', stateName: 'Massachusetts', hasStatutoryForm: true, statutoryFormCitation: 'Ch. 190B §5-501' }),
    createStateReq({ state: 'MI', stateName: 'Michigan', witnessesRequired: true, numberOfWitnesses: 2, agentCannotBeWitness: true, witnessRestrictions: 'Agent cannot serve as witness' }),
    createStateReq({ state: 'MN', stateName: 'Minnesota', hasStatutoryForm: true, statutoryFormCitation: '§523.23' }),
    createStateReq({ state: 'MS', stateName: 'Mississippi', witnessesRequired: true, numberOfWitnesses: 2, agentCannotBeWitness: true, witnessRestrictions: 'Agent cannot serve as witness' }),
    createStateReq({ state: 'MO', stateName: 'Missouri', hasStatutoryForm: true, statutoryFormCitation: '§404.710' }),
    createStateReq({ state: 'MT', stateName: 'Montana', hasStatutoryForm: true, statutoryFormCitation: '§72-31-305' }),
    createStateReq({ state: 'NE', stateName: 'Nebraska', hasStatutoryForm: true, statutoryFormCitation: '§30-4033' }),
    createStateReq({ state: 'NV', stateName: 'Nevada', hasStatutoryForm: true, statutoryFormCitation: 'NRS 162A.220' }),
    createStateReq({ state: 'NH', stateName: 'New Hampshire', strictnessLevel: 'lenient' }),
    createStateReq({ state: 'NJ', stateName: 'New Jersey', hasStatutoryForm: true, statutoryFormCitation: '§46:2B-9' }),
    createStateReq({ state: 'NM', stateName: 'New Mexico', hasStatutoryForm: true, statutoryFormCitation: '§45-5B-104' }),
    createStateReq({ state: 'ND', stateName: 'North Dakota', hasStatutoryForm: true, statutoryFormCitation: '§30.1-30-05' }),
    createStateReq({ state: 'OK', stateName: 'Oklahoma', witnessesRequired: true, numberOfWitnesses: 2, agentCannotBeWitness: true, witnessRestrictions: 'Agent cannot serve as witness' }),
    createStateReq({ state: 'OR', stateName: 'Oregon', hasStatutoryForm: true, statutoryFormCitation: '§127.005' }),
    createStateReq({ state: 'RI', stateName: 'Rhode Island', witnessesRequired: true, numberOfWitnesses: 2, agentCannotBeWitness: true, witnessRestrictions: 'Agent cannot serve as witness' }),
    createStateReq({ state: 'SC', stateName: 'South Carolina', witnessesRequired: true, numberOfWitnesses: 2, agentCannotBeWitness: true, witnessRestrictions: 'Agent cannot serve as witness', hasStatutoryForm: true, statutoryFormCitation: '§62-8-201' }),
    createStateReq({ state: 'SD', stateName: 'South Dakota', hasStatutoryForm: true, statutoryFormCitation: '§59-7-2.5' }),
    createStateReq({ state: 'UT', stateName: 'Utah', hasStatutoryForm: true, statutoryFormCitation: '§75-9-101' }),
    createStateReq({ state: 'VT', stateName: 'Vermont', hasStatutoryForm: true, statutoryFormCitation: '14 V.S.A. §3501' }),
    createStateReq({ state: 'VA', stateName: 'Virginia', witnessesRequired: true, numberOfWitnesses: 2, agentCannotBeWitness: true, witnessRestrictions: 'Agent cannot serve as witness' }),
    createStateReq({ state: 'WA', stateName: 'Washington', hasStatutoryForm: true, statutoryFormCitation: 'RCW 11.125.050' }),
    createStateReq({ state: 'WV', stateName: 'West Virginia', witnessesRequired: true, numberOfWitnesses: 2, agentCannotBeWitness: true, witnessRestrictions: 'Agent cannot serve as witness', hasStatutoryForm: true, statutoryFormCitation: '§39B-1-4' }),
    createStateReq({ state: 'WI', stateName: 'Wisconsin', hasStatutoryForm: true, statutoryFormCitation: '§243.10' }),
    createStateReq({ state: 'WY', stateName: 'Wyoming', hasStatutoryForm: true, statutoryFormCitation: '§3-5-101' }),
  ];

  await prisma.stateRequirements.createMany({ data: states });

  console.log('  ✅ Created requirements for all 51 states (12 with detailed data)');
}
