import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedStatutoryForms() {
  console.log('  📄 Seeding statutory POA forms...');

  // Check if already seeded
  const existingCount = await prisma.statutoryPOAForm.count();
  if (existingCount > 0) {
    console.log('  ⏭️  Statutory forms already seeded, skipping...');
    return;
  }

  // Priority states with required/recommended statutory forms
  const forms = [
    // Florida - REQUIRED statutory form
    {
      state: 'FL',
      formName: 'Florida Statutory Durable Power of Attorney',
      citation: 'Fla. Stat. §709.2102',
      effectiveDate: new Date('2011-10-01'),
      supersededDate: null,
      isCurrentVersion: true,
      blankFormPath: null,
      fillableForm: false,
      formInstructions: 'Must use statutory form. State rejects non-statutory POAs.',
      powerCount: 14,
      powers: [
        'Real property transactions',
        'Tangible personal property transactions',
        'Stock and bond transactions',
        'Commodity and option transactions',
        'Banking and other financial institution transactions',
        'Business operating transactions',
        'Insurance and annuity transactions',
        'Estate, trust, and other beneficiary transactions',
        'Claims and litigation',
        'Personal and family maintenance',
        'Benefits from governmental programs or civil or military service',
        'Retirement plan transactions',
        'Tax matters',
        'Digital assets'
      ],
      hasAllOption: false,
      allOptionLabel: null,
      hasGiftsRider: false,
      giftsRiderPath: null,
      requiresAgentSig: false,
      requiresSeparateAgentDoc: false,
      hasMonitors: false,
      hasCoAgents: true,
      principalNotice: 'NOTICE: THIS IS AN IMPORTANT DOCUMENT. Before signing this document, you should know these important facts...',
      agentNotice: 'When you accept the authority granted under this power of attorney, a special legal relationship is created between you and the principal...',
      witnessesRequired: '2 witnesses AND notary',
      witnessRestrictions: 'Agent cannot be witness',
      notaryRequired: true,
      notaryBlockTemplate: 'STATE OF FLORIDA\nCOUNTY OF _______________\n\nThe foregoing instrument was acknowledged before me...',
      userGuidance: 'Florida is VERY strict. Must use this exact statutory form. Hot powers require separate consent.',
      commonMistakes: 'Using custom forms (rejected), not initialing hot powers, missing witness signatures',
      uploadedById: null,
      usageCount: 0,
      lastUsedAt: null
    },

    // New York - REQUIRED statutory form
    {
      state: 'NY',
      formName: 'New York Statutory Short Form Power of Attorney',
      citation: 'Gen. Oblig. Law §5-1501',
      effectiveDate: new Date('2021-06-13'),
      supersededDate: null,
      isCurrentVersion: true,
      blankFormPath: null,
      fillableForm: false,
      formInstructions: 'Must use statutory form. Agent must sign and have signature notarized. Use Form P-2 for gifting powers.',
      powerCount: 16,
      powers: [
        'Real estate transactions',
        'Chattel and goods transactions',
        'Bond, share, and commodity transactions',
        'Banking transactions',
        'Business operating transactions',
        'Insurance transactions',
        'Estate transactions',
        'Personal relationships and affairs',
        'Benefits from governmental programs',
        'Retirement benefit transactions',
        'Tax matters',
        'Claims and litigation',
        'Commodity transactions',
        'Delegation',
        'Records, reports, and statements',
        'Full and unqualified authority'
      ],
      hasAllOption: true,
      allOptionLabel: 'Grant general authority (ALL POWERS)',
      hasGiftsRider: true,
      giftsRiderPath: 'Form P-2 (Gifts Rider)',
      requiresAgentSig: true,
      requiresSeparateAgentDoc: false,
      hasMonitors: true,
      hasCoAgents: true,
      principalNotice: 'IMPORTANT INFORMATION: This is an important document. It grants the agent broad powers...',
      agentNotice: 'AGENT DUTIES: When you accept the authority granted under this power of attorney, a special legal relationship is created...',
      witnessesRequired: 'Notary only',
      witnessRestrictions: null,
      notaryRequired: true,
      notaryBlockTemplate: 'STATE OF NEW YORK\nCOUNTY OF _______________\n\nOn this _____ day of _____________, 20___, before me personally appeared...',
      userGuidance: 'New York is VERY strict. Agent MUST sign and have signature notarized. Need separate Form P-2 for gifting.',
      commonMistakes: 'Agent not signing, gifts without Form P-2, using old pre-2021 forms',
      uploadedById: null,
      usageCount: 0,
      lastUsedAt: null
    },

    // California - Strongly recommended
    {
      state: 'CA',
      formName: 'California Uniform Statutory Form Power of Attorney',
      citation: 'Prob. Code §4401',
      effectiveDate: new Date('2015-01-01'),
      supersededDate: null,
      isCurrentVersion: true,
      blankFormPath: null,
      fillableForm: false,
      formInstructions: 'Statutory form strongly recommended but not required. Notary OR 2 witnesses required.',
      powerCount: 13,
      powers: [
        'Real property',
        'Tangible personal property',
        'Stocks and bonds',
        'Commodities and options',
        'Banks and other financial institutions',
        'Operation of entity or business',
        'Insurance and annuities',
        'Estates, trusts, and other beneficial interests',
        'Claims and litigation',
        'Personal and family maintenance',
        'Benefits from governmental programs or civil or military service',
        'Retirement plans',
        'Taxes'
      ],
      hasAllOption: true,
      allOptionLabel: 'ALL of the subjects above',
      hasGiftsRider: false,
      giftsRiderPath: null,
      requiresAgentSig: false,
      requiresSeparateAgentDoc: false,
      hasMonitors: false,
      hasCoAgents: true,
      principalNotice: 'WARNING TO PERSON EXECUTING THIS DOCUMENT: This is an important legal document...',
      agentNotice: 'Your duties when acting as agent: When you accept authority as agent, a special relationship is created...',
      witnessesRequired: 'Either 2 witnesses OR notary',
      witnessRestrictions: 'Agent and relatives cannot witness',
      notaryRequired: false,
      notaryBlockTemplate: 'A notary public or other officer completing this certificate verifies only the identity of the individual who signed...',
      userGuidance: 'California allows choice of notary OR 2 witnesses. Relatives cannot witness. Community property considerations.',
      commonMistakes: 'Using agent as witness, not understanding community property implications',
      uploadedById: null,
      usageCount: 0,
      lastUsedAt: null
    },

    // Texas - Recommended
    {
      state: 'TX',
      formName: 'Texas Statutory Durable Power of Attorney',
      citation: 'Est. Code §752.051',
      effectiveDate: new Date('2017-09-01'),
      supersededDate: null,
      isCurrentVersion: true,
      blankFormPath: null,
      fillableForm: false,
      formInstructions: 'Statutory form recommended and widely accepted. Notary only.',
      powerCount: 13,
      powers: [
        'Real property transactions',
        'Tangible personal property transactions',
        'Stock and bond transactions',
        'Commodity and option transactions',
        'Banking and other financial institution transactions',
        'Business operating transactions',
        'Insurance and annuity transactions',
        'Estate, trust, and other beneficiary transactions',
        'Claims and litigation',
        'Personal and family maintenance',
        'Benefits from governmental programs or civil or military service',
        'Retirement plan transactions',
        'Tax matters'
      ],
      hasAllOption: false,
      allOptionLabel: null,
      hasGiftsRider: false,
      giftsRiderPath: null,
      requiresAgentSig: false,
      requiresSeparateAgentDoc: false,
      hasMonitors: false,
      hasCoAgents: true,
      principalNotice: 'NOTICE TO PERSON EXECUTING THIS DOCUMENT: This is an important legal document...',
      agentNotice: 'NOTICE TO AGENT: You are responsible for managing the assets and property of the principal...',
      witnessesRequired: 'Notary only',
      witnessRestrictions: null,
      notaryRequired: true,
      notaryBlockTemplate: 'STATE OF TEXAS\nCOUNTY OF _______________\n\nThis document was acknowledged before me...',
      userGuidance: 'Texas statutory form is simple - just notary required. Community property state considerations.',
      commonMistakes: 'Spouse not consenting to homestead transactions',
      uploadedById: null,
      usageCount: 0,
      lastUsedAt: null
    },

    // Pennsylvania - Recommended
    {
      state: 'PA',
      formName: 'Pennsylvania Statutory Form Power of Attorney',
      citation: '20 Pa.C.S. §5601',
      effectiveDate: new Date('2015-01-01'),
      supersededDate: null,
      isCurrentVersion: true,
      blankFormPath: null,
      fillableForm: false,
      formInstructions: 'Statutory form recommended. Includes required agent acceptance page.',
      powerCount: 13,
      powers: [
        'Real estate',
        'Tangible personal property',
        'Stocks, bonds, and other securities',
        'Banks and financial institutions',
        'Operation of business',
        'Insurance and annuities',
        'Estates, trusts, and other beneficial interests',
        'Claims and litigation',
        'Personal and family care',
        'Government benefits',
        'Retirement plans',
        'Taxes',
        'Digital assets'
      ],
      hasAllOption: true,
      allOptionLabel: 'All Preceding Subjects',
      hasGiftsRider: false,
      giftsRiderPath: null,
      requiresAgentSig: true,
      requiresSeparateAgentDoc: false,
      hasMonitors: false,
      hasCoAgents: true,
      principalNotice: 'NOTICE: The powers granted by this document are broad...',
      agentNotice: 'NOTICE TO AGENT: As the agent, you are liable for injury...',
      witnessesRequired: '2 witnesses AND notary',
      witnessRestrictions: 'Agent cannot be witness',
      notaryRequired: true,
      notaryBlockTemplate: 'Commonwealth of Pennsylvania\nCounty of _______________\n\nOn this _____ day of _____________, 20___...',
      userGuidance: 'Pennsylvania requires agent to sign acceptance page (not notarized).',
      commonMistakes: 'Agent not signing acceptance page',
      uploadedById: null,
      usageCount: 0,
      lastUsedAt: null
    },

    // Illinois - Safe harbor form
    {
      state: 'IL',
      formName: 'Illinois Statutory Short Form Power of Attorney for Property',
      citation: '755 ILCS 45/3-3',
      effectiveDate: new Date('2010-01-01'),
      supersededDate: null,
      isCurrentVersion: true,
      blankFormPath: null,
      fillableForm: false,
      formInstructions: 'Statutory short form provides safe harbor protection.',
      powerCount: 13,
      powers: [
        'Real estate',
        'Financial institutions',
        'Stocks and bonds',
        'Tangible personal property',
        'Safe deposits',
        'Insurance',
        'Retirement plans',
        'Social Security and government benefits',
        'Tax matters',
        'Claims and litigation',
        'Commodity and option transactions',
        'Business operations',
        'Estate and trust transactions'
      ],
      hasAllOption: true,
      allOptionLabel: 'All of the above powers',
      hasGiftsRider: false,
      giftsRiderPath: null,
      requiresAgentSig: false,
      requiresSeparateAgentDoc: false,
      hasMonitors: false,
      hasCoAgents: true,
      principalNotice: 'WARNING TO PRINCIPAL: This is an important legal document...',
      agentNotice: 'NOTICE TO AGENT: When you accept the authority granted...',
      witnessesRequired: '1 witness AND notary',
      witnessRestrictions: 'Agent cannot be witness',
      notaryRequired: true,
      notaryBlockTemplate: 'STATE OF ILLINOIS\nCOUNTY OF _______________\n\nThe foregoing instrument was acknowledged before me...',
      userGuidance: 'Illinois statutory form provides safe harbor - strongly recommended.',
      commonMistakes: 'Using agent as witness, only getting notary without witness',
      uploadedById: null,
      usageCount: 0,
      lastUsedAt: null
    },

    // North Carolina - Recommended
    {
      state: 'NC',
      formName: 'North Carolina Statutory Short Form of General Power of Attorney',
      citation: '§32C-1-105',
      effectiveDate: new Date('2017-10-01'),
      supersededDate: null,
      isCurrentVersion: true,
      blankFormPath: null,
      fillableForm: false,
      formInstructions: 'Statutory form recommended. Must be recorded if used for real estate.',
      powerCount: 13,
      powers: [
        'Real property',
        'Tangible personal property',
        'Stocks and bonds',
        'Commodities and options',
        'Banks and other financial institutions',
        'Operation of entity or business',
        'Insurance and annuities',
        'Estates, trusts, and other beneficial interests',
        'Claims and litigation',
        'Personal and family maintenance',
        'Benefits from governmental programs',
        'Retirement plans',
        'Taxes'
      ],
      hasAllOption: true,
      allOptionLabel: 'All of the subjects listed above',
      hasGiftsRider: false,
      giftsRiderPath: null,
      requiresAgentSig: false,
      requiresSeparateAgentDoc: false,
      hasMonitors: false,
      hasCoAgents: true,
      principalNotice: 'NOTICE: The powers granted by this document are broad...',
      agentNotice: 'IMPORTANT INFORMATION FOR AGENT: When you accept the authority...',
      witnessesRequired: '2 witnesses AND notary',
      witnessRestrictions: 'Agent cannot be witness',
      notaryRequired: true,
      notaryBlockTemplate: 'STATE OF NORTH CAROLINA\nCOUNTY OF _______________\n\nI certify that the following person personally appeared...',
      userGuidance: 'Must be recorded with Register of Deeds if used for real estate transactions.',
      commonMistakes: 'Not recording when used for real estate',
      uploadedById: null,
      usageCount: 0,
      lastUsedAt: null
    }
  ];

  // Create statutory forms
  for (const form of forms) {
    await prisma.statutoryPOAForm.create({
      data: form
    });
  }

  console.log('  ✅ Created statutory forms for 7 priority states');
}
